Algoritmo "circulo_exercicio"
//
//
// Descrição   : exercicio parte estrutural
// Autora    : Fabiola
// Data atual  : 16-10-2022
Var

   raioC, area, x, y, p : real


Inicio


      escreval("Exercício Circulo")
      escreval()
      escreval("Digite o valor do raio do circulo:")
      leia(x)

      y <-2
      p <- Pi
      
      raioC <- Exp(x, y)
      
      area <- p*raioC
      
      escreval("AREA: ", area:8:3)



Fimalgoritmo