Algoritmo "consumo_exerc1"
//
//
// Descrição   : exercicio parte estrutural
// Autora    : Fabiola
// Data atual  : 16-10-2022
Var

   distancia, gasto, consumo : real


Inicio


      escreval("Exercício CONSUMO")
      escreval()
      escreval("Distância percorrida : ")
      leia(distancia)
      escreval("Combustível gasto : ")
      leia(gasto)
      escreval()


      consumo <- (distancia/gasto)

      escreval("Consumo médio ", consumo:8:3)

Fimalgoritmo