Algoritmo "senha_fixa"
// 
//
// Descrição   : licao estrutura
// Autor(a)    : Fabiola
// Data atual  : 21-10-2022


Var

    senha: inteiro

Inicio

    senha<-0
    escreva("Digite a senha: ")
    leia(senha)
    
    enquanto senha<>2002 faca

      escreva("Senha Inválida!Tente novamente: ")
      leia(senha)

    fimenquanto

    escreva("Acesso permitido!")


Fimalgoritmo