Algoritmo "sequencia_impares"
// 
//  
// Descrição   : Estudo Lógica Programação UDEMY
// Autor(a)    : Fabiola
// Data atual  : 24-10-2022
//
//
Var

   valor, i: inteiro

Inicio

      escreva("Digite o valor de X: ")
      leia(valor)


      para i de 1 ate valor faca
          se i % 2<>0 entao

          escreval(i)
          
          fimse
      fimpara


Fimalgoritmo