Algoritmo "tabuada"
// 
//  
// Descrição   : Estudo Lógica Programação UDEMY
// Autor(a)    : Fabiola
// Data atual  : 24-10-2022
//
//
Var

      valor,varia, resultado :inteiro

Inicio

      escreva("Deseja a tabuada para qual valor? ")
      leia(valor)
      
      para varia de 1 até 10 faca
      resultado <- valor*varia
      escreval(valor, " X ",varia, " =", resultado)
      
      fimpara


Fimalgoritmo