Algoritmo "teste_enquanto"
//
//
// Descrição   : exercicio parte estrutural
// Autora    : Fabiola
// Data atual  : 20-10-2022
//
//
Var

   x, soma: inteiro

Inicio

      soma <- 0
      escreva("Digite o primeiro numero: ")
      leia(x)
      
      enquanto x <> 0 faca
         soma <- soma + x
         escreva("Digite o primeiro numero: ")
         leia(x)
      fimenquanto
      
      escreval("SOMA =  ", soma)



Fimalgoritmo